name: 'Validate Helm Releases'

'on':
  pull_request:
    paths:
      - 'kubernetes/**-chart.yaml'
  push:
    paths:
      - 'kubernetes/**-chart.yaml'
    tags-ignore:
      - 'flux-sync'

jobs:
  hrval:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v2'
      - uses: 'stefanprodan/hrval-action@v3.3.1'
        with:
          helmVersion: 'v3'
          helmRelease: 'kubernetes/'
          kubernetesVersion: '1.17.9'
